layout_spectrum: 0.2892979218158871
typography_spectrum: 0.6629791317973286
color:
  brandStrength: 0.9372824458405375
  lightness: 0.26370190223678946
  saturation: 0.5368868955411017
  rhythmicContrast: 0.027835502987727523
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
author:
  name: Aisha & Daniel Flores
  email: info@azaleacg.com
  url: www.azaleacreativegroup.com
name: Azalea Creative Group
title: From Bloom to Boom!
